# birdnet-market-ngtukien — dev | image test nhẹ: traefik/whoami
components:
  app:
    image:
      repository: traefik/whoami
      tag: "v1.10.3"
    replicaCount: 1
    port: 80
    httpRoute:
      enabled: true
      hostnames: ["birdnet-market-ngtukien-dev.duongot.work"]
      pathPrefixes: ["/"]
sealedSecret:
  enabled: false
